### ISSUE TITLE
Order Sim Card for Test Device (Mr. Tappy)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-user-experience-testing#9]
Our "Test" iPhone `should` have SIM Card in it so that we can test apps on 3G/4G to give a _realistic_ load time for our tests.

Thinking of ordering one from 3 Network: 
![image](https://cloud.githubusercontent.com/assets/194400/26006454/5485a658-3734-11e7-9392-befa2ae6d296.png)
http://www.three.co.uk/Store/SIM/Plans_for_phones#?contract=1&data=&minutes=&type=alltype
1-month Rolling Contract. 1GB Data.

**Comment by iteles** [comment]
![do-it-gif](https://media.giphy.com/media/wi8Ez1mwRcKGI/giphy.gif)

**Comment by njsfield** [comment]
[uSwitch - iD is cheapest at £5 per month (rolling)](https://www.uswitch.com/mobiles/compare/sim_only_deals/?ref=google~Shop~Sim_Only&gclid=CKub0dar79MCFaWw7Qod6K8PGg)

![image](https://cloud.githubusercontent.com/assets/16468314/26033516/07424fae-38a6-11e7-828f-9d93ed87f851.png)

Their [coverage](https://www.idmobile.co.uk/help-and-advice/uk-coverage-checker) for Mile End;
![image](https://cloud.githubusercontent.com/assets/16468314/26033540/6e13904e-38a6-11e7-809a-fbc77409d6e4.png)

Which is the same as [Three's](http://www.three.co.uk/Discover/Network/Coverage) coverage;
![image](https://cloud.githubusercontent.com/assets/16468314/26033555/a8bcd232-38a6-11e7-8596-f477be2f498a.png)

**Comment by nelsonic** [comment]
@njsfield yeah, the 3 network is _definitely_ not the "_cheapest_". 
(_which is why we don't **currently** use them..._)
But the _real_ question (_and criteria I should have specified in my original description_) is:

> _Which network offers the best **value-for-money** `&&` lets us **Use UK Data Allowance Abroad** (without additional charges)_?

Given that the [EU "Anti Roaming Charges" law](http://europa.eu/rapid/press-release_MEMO-17-885_en.htm) comes into effect on **15th June 2017**:
https://www.uswitch.com/mobiles/guides/mobile-roaming-charges/#eu_roaming
![image](https://cloud.githubusercontent.com/assets/194400/26413016/8b07bc3a-40a2-11e7-8aa8-635a7005176b.png)
Something that the EU _Bureaucrazy_ got _right_! 😉 

This won't be a concern anymore so iD Mobile will be a good `<option>`!
Thanks for sharing! 🎉

**Comment by nelsonic** [comment]
I've decided to switch my _personal_ mobile phone to 3 instead of getting a Sim Card for the "Test" Phone. 👍 
see: https://github.com/dwyl/remote-working/issues/12
